### ISSUE TITLE
Pagination interferes with filter mechanism

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-sitewidecontent-report#31] opened 2018-03-26 04:24 UTC
When filtering by subsite, the overall results and pages are not updated correctly.

For instance, the below screenshot - taken from the all subsites report - shows that there is more than one page on the Second Subsite:

![image](https://user-images.githubusercontent.com/14869519/37886591-c346a9dc-3118-11e8-9a8c-59f3a42ddfc9.png)

When applying the filter, only one page is shown however:

![image](https://user-images.githubusercontent.com/14869519/37886594-c75b9474-3118-11e8-8048-05fe77bb816a.png)

Note that it still says View 1 -15 of 29 in the bottom right corner.

In SilverStripe 4, when moving forward or backward through the pagination menu, results for all subsites are shown on the next page even if a filter is applied. When one choses a specific subsite, moves to the last page of results and then choses another subsite to filter on, the correct number of pages within the latter is shown. 

Versions to reproduce:
```
silverstripe/sitewidecontent-report       dev-master 60fb92c 
silverstripe/recipe-cms                   1.1.x-dev c2b64c0 
```
as well as
```
silverstripe/sitewidecontent-report       2.0.4 
silverstripe/cms                          3.6.5
```

**Comment by dhensby** [comment] 2018-03-26 13:02
is this a manifestation of https://github.com/silverstripe/silverstripe-framework/issues/5995 ?

**Comment by robbieaverill** [comment] 2019-03-07 00:51
I think this is because the filters are done with dynamic javascript rather than the report's filtering API. This also means that exporting to CSV doesn't work, etc. This should be fixed with #38.

**Comment by NightJar** [comment] 2019-03-07 02:03
By "should be fixed" do you mean "I tested this as part of my development and I can confirm the PR will fix this issue" @robbieaverill - or does it need verification by independent testing?

**Comment by robbieaverill** [comment] 2019-03-07 02:04
I did zero testing to validate my claim

**Comment by NightJar** [comment] 2019-03-07 02:05
Neat, I'll leave this open for now, until such time as we can test it (probably tomorrow).

**Comment by robbieaverill** [comment] 2019-03-07 19:58
Yep, this is fixed now

**Closed by robbieaverill** 2019-03-07 19:58 UTC
Labels: affects/v3, affects/v4, change/patch, effort/medium, impact/medium, type/UX, type/bug
